# Generated by Django 3.2.9 on 2021-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('howToCook', models.URLField()),
                ('picture', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='aliments',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
