# Generated by Django 3.2.9 on 2021-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeApp', '0002_auto_20211121_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recettes',
            name='howToCook',
            field=models.CharField(max_length=1000),
        ),
    ]
