# Generated by Django 3.2.9 on 2021-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeApp', '0003_alter_recettes_howtocook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recettes',
            name='howToCook',
            field=models.URLField(),
        ),
    ]
