# Generated by Django 3.2.9 on 2021-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeApp', '0004_alter_recettes_howtocook'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettes',
            name='aliments',
            field=models.ManyToManyField(blank=True, related_name='recettes', to='FridgeApp.Aliments'),
        ),
    ]
