# Generated by Django 3.2.9 on 2021-11-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeApp', '0005_recettes_aliments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliments',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
