# frigo


from FridgeApp.models import Aliments
farine = Aliments(name="Farine")
farine.save()
muscade = Aliments(name="Muscade")
muscade.save()
bacon = Aliments(name="Bacon")
bacon.save()
paprika = Aliments(name="Paprika")
paprika.save()
basilic = Aliments(name="Basilic")
basilic.save()
curry = Aliments(name="Curry")
curry.save()
laitConcentre = (name="Lait concentré")
laitConcentre.save()
huileOlives  = Aliments(name="Huile d'Olives")
huileOlives.save()
cubeBouillon = Aliments(name="Cube de bouillon")
cubeBouillon.save()
persil = Aliments(name='Persil')
persil.save()
cassonade = Aliments(name="Cassonade")
cassonade.save()
viandeHachee = Aliments(name = "Viande Hachée")
viandeHachee.save()
chapelure = Aliments(name="Chapelure")
chapelure.save()
siropDeLiege = Aliments(name="Sirop de Liège")
siropDeLiege.save()
citron = Aliments(name="Citron")
citron.save()
fondDeSaucePoisson = Aliments(name = "Sauce de fond poisson")
fondDeSaucePoisson.save()
thym = Aliments(name="Thym")
thym.save()
bouquetGarni = Aliments(name="Bouquet garni")
bouquetGarni.save()
ketchup = Aliments(name="Ketchup")
ketchup.save()
lardFume = Aliments(name="Lard fumé")
lardFume.save()
painDEpices = Aliments(name="Pain d'épices")
painDEpices.save()
viandeDeBoeuf = Aliments(name="Viande de boeuf")
viandeDeBoeuf.save()
biereBrune = Aliments(name="Bière brune")
biereBrune.save()
moutarde = Aliments(name="Moutarde")
moutarde.save()
vinaigreDeRiz = Aliments(name="Vinaigre de riz")
vinaigreDeRiz.save()
maizena = Aliments(name="Maïzena")
maizena.save()
filetDePoulet = Aliments(name="Filets de poulet")
filetDePoulet.save()
herbesDeProvence = Aliments(name="Herbes de Provence") 
herbesDeProvence.save()


cremeFraiche = Aliments.objects.get(name="Crème fraiche")
cremeFraiche.save()
reblechon = Aliments.objects.get(name="Reblechon")
reblechoniche.save()
beurre = Aliments.objects.get(name="Beurre")
beurreiche.save()
oeuf = Aliments.objects.get(name="Oeufs")
oeufiche.save()
lait = Aliments.objects.get(name="Lait")
laitiche.save()
gruyereRape = Aliments.objects.get(name="Gruyère râpé")
gruyereRapeiche.save()
parmesanrapa = Aliments.objects.get(name="Parmesan rapé")
parmesanrapaiche.save()
jambon = Aliments.objects.get(name="Jambon")
jamboniche.save()
pates = Aliments.objects.get(name="Pâtes")
patesiche.save()
riz = Aliments.objects.get(name="Riz")
riziche.save()
pommeDeTerre = Aliments.objects.get(name="Pomme de terre")
pommeDeTerreiche.save()
carotte = Aliments.objects.get(name="Carottes")
carotteiche.save()
courgette = Aliments.objects.get(name="Courgettes")
courgetteiche.save()
poivron = Aliments.objects.get(name="Poivron")
poivroniche.save()
epinard = Aliments.objects.get(name="Epinard")
epinardiche.save()
champignon = Aliments.objects.get(name="champignon")
champignoniche.save()
navet = Aliments.objects.get(name="navet")
navetiche.save()
aubergine= Aliments.objects.get(name="Aubergine")
aubergineiche.save()
choufleur= Aliments.objects.get(name="Choux fleur")
choufleuriche.save()
chouDeBruxelles= Aliments.objects.get(name="Choux de Bruxelles")
chouDeBruxellesiche.save()
endive = Aliments.objects.get(name="Endive")
endiveiche.save()
haricot = Aliments.objects.get(name="Haricot")
haricotiche.save()
ail= Aliments.objects.get(name="Ail")
ailiche.save()
oignon = Aliments.objects.get(name="Oignons")
oignoniche.save()
echalote = Aliments.objects.get(name="Echalote")
echaloteiche.save()
orange = Aliments.objects.get(name="Orange")
orange.save()