# frigo


cremeFraiche = Aliment(name="Crème fraiche")
cremeFraiche.save()
reblechon = Aliments(name="Reblechon")
reblechon.save()
beurre = Aliments(name="Beurre")
beurre.save()
oeuf = Aliments(name="Oeufs")
oeuf.save()
lait = Aliments(name="Lait")
lait.save()
gruyereRape = Aliments(name="Gruyère râpé")
gruyereRape.save()
parmesanrapa = Aliments(name="Parmesan rapé")
parmesanrapa.save()
jambon = Aliments(name="Jambon")
jambon.save()
pates = Aliments(name="Pâtes")
pates.save()
riz = Aliments(name="Riz")
riz.save()
pommeDeTerre = Aliments(name="Pomme de terre")
pommeDeTerre.save()
carotte = Aliments(name="Carottes")
carotte.save()
courgette = Aliments(name="Courgettes")
courgette.save()
poivron = Aliments(name="Poivron")
poivron.save()
epinard = Aliments(name="Epinard")
epinard.save()
champignon = Aliments(name="champignon")
champignon.save()
navet = Aliments(name="navet")
navet.save()
aubergine= Aliments(name="Aubergine")
aubergine.save()
choufleur= Aliments(name="Choux fleur")
choufleur.save()
chouDeBruxelles= Aliments(name="Choux de Bruxelles")
chouDeBruxelles.save()
endive = Aliments(name="Endive")
endive.save()
haricot = Aliments(name="Haricot")
haricot.save()
ail= Aliments(name="Ail")
ail.save()
oignon = Aliments(name="Oignons")
oignon.save()
echalote = Aliments(name="Echalote")
echalote.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
= Aliments(name="")
.save()
# epices
sel= Aliments(name="Sel")
sel.save()
poivre= Aliments(name="Poivre")
poivre.save()
basilic= Aliments(name="Basilic")
basilic.save()
persil = Aliments(name="Persil")
persil.save()
origan = Aliments(name="Origan")
origan.save()
muscade= Aliments(name="Muscade")
muscade.save()
= Aliments(name="")
.save()
