# frigo


from FridgeApp.models import Aliments
farine = Aliments(name="Farine")
farine.save()
muscade = Aliments(name="Muscade")
muscade.save()
bacon = Aliments(name="Bacon")
bacon.save()
paprika = Aliments(name="Paprika")
paprika.save()
basilic = Aliments(name="Basilic")
basilic.save()
curry = Aliments(name="Curry")
curry.save()
laitConcentre = (name="Lait concentré")
laitConcentre.save()
huileOlives  = Aliments(name="Huile d'Olives")
huileOlives.save()
cubeBouillon = Aliments(name="Cube de bouillon")
cubeBouillon.save()
persil = Aliments(name='Persil')
persil.save()
cassonade = Aliments(name="Cassonade")
cassonade.save()
viandeHachee = Aliments(name = "Viande Hachée")
viandeHachee.save()
chapelure = Aliments(name="Chapelure")
chapelure.save()
siropDeLiege = Aliments(name="Sirop de Liège")
siropDeLiege.save()
citron = Aliments(name="Citron")
citron.save()
fondDeSaucePoisson = Aliments(name = "Sauce de fond poisson")
fondDeSaucePoisson.save()
thym = Aliments(name="Thym")
thym.save()
bouquetGarni = Aliments(name="Bouquet garni")
bouquetGarni.save()
ketchup = Aliments(name="Ketchup")
ketchup.save()
lardFume = Aliments(name="Lard fumé")
lardFume.save()
painDEpices = Aliments(name="Pain d'épices")
painDEpices.save()
viandeDeBoeuf = Aliments(name="Viande de boeuf")
viandeDeBoeuf.save()
biereBrune = Aliments(name="Bière brune")
biereBrune.save()
moutarde = Aliments(name="Moutarde")
moutarde.save()
vinaigreDeRiz = Aliments(name="Vinaigre de riz")
vinaigreDeRiz.save()
maizena = Aliments(name="Maïzena")
maizena.save()
filetDePoulet = Aliments(name="Filets de poulet")
filetDePoulet.save()
herbesDeProvence = Aliments(name="Herbes de Provence") 
herbesDeProvence.save()

