# frigo


from FridgeApp.models import Aliments
farine = Aliments(name="Farine")
farine.save()
muscade = Aliments(name="Muscade")
muscade.save()
bacon = Aliments(name="Bacon")
bacon.save()
paprika = Aliments(name="Paprika")
paprika.save()
basilic = Aliments(name="Basilic")
basilic.save()
curry = Aliments(name="Curry")
curry.save()
laitConcentre = (name="Lait concentré")
laitConcentre.save()
huileOlives  = Aliments(name="Huile d'Olives")
huileOlives.save()
cubeBouillon = Aliments(name="Cube de bouillon")
cubeBouillon.save()
persil = Aliments(name='Persil')
persil.save()
cassonade = Aliments(name="Cassonade")
cassonade.save()
viandeHachee = Aliments(name = "Viande Hachée")
viandeHachee.save()
chapelure = Aliments(name="Chapelure")
chapelure.save()
siropDeLiege = Aliments(name="Sirop de Liège")
siropDeLiege.save()
citron = Aliments(name="Citron")
citron.save()
fondDeSaucePoisson = Aliments(name = "Sauce de fond poisson")
fondDeSaucePoisson.save()
thym = Aliments(name="Thym")
thym.save()
bouquetGarni = Aliments(name="Bouquet garni")
bouquetGarni.save()
ketchup = Aliments(name="Ketchup")
ketchup.save()
lardFume = Aliments(name="Lard fumé")
lardFume.save()
painDEpices = Aliments(name="Pain d'épices")
painDEpices.save()
viandeDeBoeuf = Aliments(name="Viande de boeuf")
viandeDeBoeuf.save()
biereBrune = Aliments(name="Bière brune")
biereBrune.save()
moutarde = Aliments(name="Moutarde")
moutarde.save()
vinaigreDeRiz = Aliments(name="Vinaigre de riz")
vinaigreDeRiz.save()
maizena = Aliments(name="Maïzena")
maizena.save()
filetDePoulet = Aliments(name="Filets de poulet")
filetDePoulet.save()
herbesDeProvence = Aliments(name="Herbes de Provence") 
herbesDeProvence.save()


chiconGratin= Recettes.objects.get(name ="Chicon aux gratin")
chiconGratin.aliments.add(jambon,endive, farine,lait,sel,muscade,beurre,gruyereRape)
gratinDePateAuJambon = Recettes.objects.get(name ="Gratin de pâtes au jambon")
gratinDePateAuJambon.aliments.add(pates,jambon,gruyereRape,lait,farine,sel,poivre,muscade)

omeletteCampagnarde = Recettes.objects.get(name ="Omelette forestière")
omeletteCampagnarde.aliments.add(pommeDeTerre,champignon,basilic,,paprika,oeuf,sel,poivre,bacon,oignon)
soupeDeHaricotVert = Recettes.objects.get(name ="Soupe de haricots verts")
soupeDeHaricotVert.aliments.add(courgette,cubeBouillon,laitConcentre,curry,poivre,parmesanRape,huileOlives,curry,haricot,oignon)
gratindeCourgette = Recettes.objects.get(name ="Gratin de Courgettes")
gratindeCourgette.aliments.add(courgette,sel,poivre,oignon,beurre,cremeFraiche,gruyereRape,oeuf)
bouletsALaLiegeoise= Recettes.objects.get(name ="Boulette à la Liégeoise")
bouletsALaLiegeoise.aliments.add(viandeHachee,farine,cassonade,sel,poivre,siropDeLiege,persil,oeuf,oignon,echalotte,chapelure)
cabillaudEnPapillote = Recettes.objects.get(name ="Cabillaud en papillotes")
cabillaudEnPapillote.aliments.add(huileOlives,fondDeSaucePoisson,thym,cabillaud,citron,poivre)
carbonadeFlamande = Recettes.objects.get(name ="Carbonades à la Flamande")
carbonadeFlamande.aliments.add(beurre,oignon,sel,moutarde,viandeDeBoeuf,biereBrune,painDEpices,lardFume,cassonade,bouquetGarni,)
pouletAigreDoux = Recettes.objects.get(name ="Ooulet aigre-doux")
pouletAigreDoux.aliments.add(vinaigreDeRiz,cassonade,ketchup,cubeBouillon,maizena,fondDeSaucePoisson ,carotte,oignon,sel,poivre,tomate,filetDePoulet,huileOlives)
tomatesFarcies = Recettes.objects.get(name ="Tomates farcies")
tomatesFarcies.aliments.add(tomate,ail,thym,persil,sel,viandeHachee,oignon,poivre,beurre)
hachisParmentier = Recettes.objects.get(name ="Hachis Parmentier")
hachisParmentier.aliments.add(pommeDeTerre,ail,farine,tomate,herbesDeProvence,parmesanRape,sel,poivre,viandeHachee,oignon,beurre,oeuf,)

